---
# tasks file for mysql_db
- name: install mysql
  apt: 
    state: present
    name: "{{ item }}"
  loop:
    - mysql-server
    - mysql-client
  when: ansible_os_family == 'Debian'
    
- name: start mysql
  service:
    name: mysql
    state: started
    enabled: yes

- name: create db
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

    
- name: create user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'